/* Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. · https://www.zhuatech.cn/ */
package cn.zhuatech.tax.service;
import cn.zhuatech.tax.common.BusinessException; import cn.zhuatech.tax.dto.TaxDto.*; import cn.zhuatech.tax.model.*; import cn.zhuatech.tax.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @Transactional(readOnly=true) public class TaxService {
    private final TaxFilingRepository orders; private final TaxLedgerRecordRepository reports; private final TaxRuleRepository taxRule; private final TaxRiskRepository taxRisks; private final CurrentUserService current;
    public TaxService(TaxFilingRepository orders,TaxLedgerRecordRepository reports,TaxRuleRepository taxRule,TaxRiskRepository taxRisks,CurrentUserService current){this.orders=orders;this.reports=reports;this.taxRule=taxRule;this.taxRisks=taxRisks;this.current=current;}
    public Dashboard shopfloorDashboard(){String center=current.get().getTaxEntityCode();List<TaxFiling> list=center==null?orders.findAllByOrderByDueDateAsc():orders.findByTaxEntityCodeOrderByDueDateAsc(center);return dashboard(list);}
    public Dashboard adminDashboard(){return dashboard(orders.findAllByOrderByDueDateAsc());}
    public List<TaxFilingView> taxFilings(){return orders.findAllByOrderByDueDateAsc().stream().map(this::view).toList();}
    @Transactional public ReportResult report(Long id,ReportRequest request){TaxFiling order=orders.findById(id).orElseThrow(()->new BusinessException("申报任务不存在"));if(order.getStatus()==TaxFiling.Status.COMPLETED)throw new BusinessException("已完成任务不能继续反馈");if(order.getCompletedQty()+request.goodQty()>order.getPlannedQty())throw new BusinessException("完成数量不能超过任务剩余数量");order.report(request.goodQty(),request.defectQty());reports.save(new TaxLedgerRecord(order,request.operationName(),request.goodQty(),request.defectQty(),current.get().getFullName(),request.remark()));return new ReportResult(order.getOrderNo(),order.getCompletedQty(),order.getDefectQty(),progress(order),order.getStatus().name());}
    private Dashboard dashboard(List<TaxFiling> list){int planned=list.stream().mapToInt(TaxFiling::getPlannedQty).sum(),done=list.stream().mapToInt(TaxFiling::getCompletedQty).sum(),defects=list.stream().mapToInt(TaxFiling::getDefectQty).sum();int rate=planned==0?0:Math.round(done*100f/planned);List<Metric> metrics=List.of(new Metric("今日申报",String.format("%,d",planned),list.size()+" 张申报任务","blue"),new Metric("申报完成率",rate+"%",String.format("%,d / %,d",done,planned),"green"),new Metric("结果税务合规率",String.format("%.1f%%",done+defects==0?100d:done*100d/(done+defects)),defects+" 项异常","warn"),new Metric("税务规则异常",taxRule.countByStatus(TaxRule.Status.ALARM)+"",taxRisks.countByResult(TaxRisk.Result.PENDING)+" 项待复核","red"));return new Dashboard(metrics,list.stream().map(this::view).toList(),taxRule.findAllByOrderByCodeAsc().stream().map(e->new ControlView(e.getCode(),e.getName(),e.getTaxEntity().getName(),e.getStatus().name(),e.getOee(),e.getLastHeartbeat())).toList(),taxRisks.findTop10ByOrderByIdDesc().stream().map(i->new TaxRiskView(i.getTaxRiskNo(),i.getTaxFiling().getOrderNo(),i.getTaxFiling().getProductName(),i.getTaxRiskType(),i.getTaxRiskQty(),i.getDefectQty(),i.getResult().name(),i.getInspector())).toList());}
    private TaxFilingView view(TaxFiling o){return new TaxFilingView(o.getId(),o.getOrderNo(),o.getProductCode(),o.getProductName(),o.getTaxEntity().getName(),o.getTaxEntity().getWorkshop(),o.getPlannedQty(),o.getCompletedQty(),o.getDefectQty(),o.getDueDate(),o.getStatus().name(),o.getBatchNo(),progress(o));}
    private int progress(TaxFiling o){return o.getPlannedQty()==0?0:Math.min(100,Math.round(o.getCompletedQty()*100f/o.getPlannedQty()));}
}
